apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:9090
   version: 1
   editable: true
 - name: PostgreSQL
   type: postgres
   access: proxy
   orgId: 1
   url: postgres:5432
   database: postgres
   user: postgres
   jsonData:
     sslmode: disable
   secureJsonData:
     password: flows
   version: 1
   editable: true